//
//  NewsFeedPresenter.swift
//  VkFeed
//
//  Created by Ivan0v42 on 07.06.2020.
//  Copyright (c) 2020 Mac. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsFeedPresentationLogic
{
  func presentSomething(response: NewsFeed.Something.Response)
}

class NewsFeedPresenter: NewsFeedPresentationLogic
{
  weak var viewController: NewsFeedDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: NewsFeed.Something.Response)
  {
    let viewModel = NewsFeed.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
