//
//  NewsFeedInteractor.swift
//  VkFeed
//
//  Created by Ivan0v42 on 07.06.2020.
//  Copyright (c) 2020 Mac. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsFeedBusinessLogic
{
  func doSomething(request: NewsFeed.Something.Request)
}

protocol NewsFeedDataStore
{
  //var name: String { get set }
}

class NewsFeedInteractor: NewsFeedBusinessLogic, NewsFeedDataStore
{
  var presenter: NewsFeedPresentationLogic?
  var worker: NewsFeedWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: NewsFeed.Something.Request)
  {
    worker = NewsFeedWorker()
    worker?.doSomeWork()
    
    let response = NewsFeed.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
